Program(
  Declaration(
    Array_Declaration(
      Data_Type(
        bool
      ),
      IDENTIFIER: "array",
      Const(
        INTEGER_LITERAL: "5"
      ),
      Argument_List(
        Factor(
          Const(
            INTEGER_LITERAL: "1"
          )
        ),
        Factor(
          Const(
            INTEGER_LITERAL: "2"
          )
        )
      )
    )
  ),
  Declaration(
    Array_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "array",
      Const(
        INTEGER_LITERAL: "10"
      )
    )
  ),
  Declaration(
    Variable_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "a",
      IDENTIFIER: "b",
      IDENTIFIER: "c"
    )
  ),
  Declaration(
    Variable_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "d",
      Factor(
        Const(
          INTEGER_LITERAL: "5"
        )
      )
    )
  ),
  Declaration(
    Variable_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "c",
      Factor(
        IDENTIFIER: "bar",
        Argument_List(
          Factor(
            Const(
              INTEGER_LITERAL: "1000"
            )
          ),
          Factor(
            Const(
              INTEGER_LITERAL: "2"
            )
          ),
          Factor(
            Const(
              INTEGER_LITERAL: "3"
            )
          )
        )
      )
    )
  ),
  Declaration(
    Variable_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "b",
      Factor(
        IDENTIFIER: "a"
      )
    )
  ),
  Declaration(
    Function_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "isValid",
      Parameter_List(
        Data_Type(
          bool
        ),
        IDENTIFIER: "x",
        Data_Type(
          int
        ),
        IDENTIFIER: "y",
        Data_Type(
          char
        ),
        IDENTIFIER: "z"
      )
    )
  ),
  Declaration(
    Function_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "empty",
      Parameter_List()
    )
  ),
  Declaration(
    Function_Declaration(
      Data_Type(
        int
      ),
      IDENTIFIER: "main",
      Parameter_List(),
      Block(
        Block_Item_List(
          Block_Item(
            Statement(
              Input_Statement(
                STRING: %d
              )
            )
          ),
          Block_Item(
            Statement(
              Input_Statement(
                STRING: dog
              )
            )
          ),
          Block_Item(
            Statement(
              Input_Statement(
                STRING: %f,
                IDENTIFIER: "value"
              )
            )
          ),
          Block_Item(
            Statement(
              Input_Statement(
                STRING: %f %f,
                IDENTIFIER: "value1",
                IDENTIFIER: "value2"
              )
            )
          ),
          Block_Item(
            Statement(
              Input_Statement(
                STRING:  
              )
            )
          ),
          Block_Item(
            Statement(
              Output_Statement(
                STRING: Hello, Universe!
              )
            )
          ),
          Block_Item(
            Statement(
              Output_Statement(
                IDENTIFIER: "name"
              )
            )
          ),
          Block_Item(
            Statement(
              Output_Statement(
                STRING: Hello, your grade is %d %d,
                Factor(
                  IDENTIFIER: "grade"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Output_Statement(
                STRING: Hello, your grade is %d %d,
                Factor(
                  IDENTIFIER: "grade"
                ),
                Factor(
                  IDENTIFIER: "year"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              If_Statement(
                Factor(
                  Const(
                    true
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Statement(
                        Return_Statement(
                          Factor(
                            Const(
                              INTEGER_LITERAL: "0"
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              If_Statement(
                Factor(
                  Const(
                    false
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Variable_Declaration(
                        Data_Type(
                          bool
                        ),
                        IDENTIFIER: "a"
                      )
                    )
                  )
                ),
                Else_Clause(
                  Block(
                    Block_Item_List(
                      Block_Item(
                        Variable_Declaration(
                          Data_Type(
                            bool
                          ),
                          IDENTIFIER: "b"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              If_Statement(
                Factor(
                  Const(
                    false
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Statement(
                        Return_Statement(
                          Factor(
                            Const(
                              INTEGER_LITERAL: "0"
                            )
                          )
                        )
                      )
                    )
                  )
                ),
                Else_Clause(
                  If_Statement(
                    Factor(
                      Const(
                        true
                      )
                    ),
                    Block(
                      Block_Item_List(
                        Block_Item(
                          Variable_Declaration(
                            Data_Type(
                              int
                            ),
                            IDENTIFIER: "a"
                          )
                        )
                      )
                    ),
                    Else_Clause(
                      If_Statement(
                        Factor(
                          Const(
                            INTEGER_LITERAL: "1000"
                          )
                        ),
                        Block(
                          Block_Item_List(
                            Block_Item(
                              Variable_Declaration(
                                Data_Type(
                                  int
                                ),
                                IDENTIFIER: "b"
                              )
                            )
                          )
                        ),
                        Else_Clause(
                          Block(
                            Block_Item_List(
                              Block_Item(
                                Variable_Declaration(
                                  Data_Type(
                                    int
                                  ),
                                  IDENTIFIER: "c"
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              If_Statement(
                Factor(
                  Const(
                    false
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Statement(
                        If_Statement(
                          Factor(
                            Const(
                              true
                            )
                          ),
                          Block(
                            Block_Item_List(
                              Block_Item(
                                Variable_Declaration(
                                  Data_Type(
                                    int
                                  ),
                                  IDENTIFIER: "test"
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                ),
                Else_Clause(
                  Block(
                    Block_Item_List(
                      Block_Item(
                        Variable_Declaration(
                          Data_Type(
                            bool
                          ),
                          IDENTIFIER: "b"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              For_Statement(
                Variable_Declaration(
                  Data_Type(
                    int
                  ),
                  IDENTIFIER: "i",
                  Factor(
                    Const(
                      INTEGER_LITERAL: "0"
                    )
                  )
                ),
                Factor(
                  IDENTIFIER: "less_than",
                  Argument_List(
                    Factor(
                      IDENTIFIER: "i"
                    )
                  )
                ),
                Factor(
                  IDENTIFIER: "increment",
                  Argument_List(
                    Factor(
                      IDENTIFIER: "i"
                    )
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Variable_Declaration(
                        Data_Type(
                          int
                        ),
                        IDENTIFIER: "result",
                        Factor(
                          Const(
                            INTEGER_LITERAL: "2"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              For_Statement(
                Variable_Declaration(
                  Data_Type(
                    int
                  ),
                  IDENTIFIER: "i",
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  )
                ),
                Factor(
                  IDENTIFIER: "i"
                ),
                Factor(
                  IDENTIFIER: "i"
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Statement(
                        For_Statement(
                          Variable_Declaration(
                            Data_Type(
                              int
                            ),
                            IDENTIFIER: "j",
                            Factor(
                              Const(
                                INTEGER_LITERAL: "0"
                              )
                            )
                          ),
                          Factor(
                            IDENTIFIER: "j"
                          ),
                          Factor(
                            IDENTIFIER: "j"
                          ),
                          Block(
                            Block_Item_List(
                              Block_Item(
                                Variable_Declaration(
                                  Data_Type(
                                    int
                                  ),
                                  IDENTIFIER: "testing",
                                  Factor(
                                    Const(
                                      INTEGER_LITERAL: "5"
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              While_Statement(
                Factor(
                  Const(
                    false
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Statement(
                        Return_Statement(
                          Factor(
                            Const(
                              false
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              While_Statement(
                Factor(
                  Const(
                    true
                  )
                ),
                Block(
                  Block_Item_List(
                    Block_Item(
                      Variable_Declaration(
                        Data_Type(
                          int
                        ),
                        IDENTIFIER: "a"
                      )
                    ),
                    Block_Item(
                      Statement(
                        While_Statement(
                          Factor(
                            Const(
                              INTEGER_LITERAL: "5"
                            )
                          ),
                          Block(
                            Block_Item_List(
                              Block_Item(
                                Statement(
                                  Expression_Statement(
                                    Factor(
                                      Const(
                                        INTEGER_LITERAL: "5"
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    ),
                    Block_Item(
                      Statement(
                        Return_Statement(
                          Factor(
                            Const(
                              true
                            )
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "value"
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                char
              ),
              IDENTIFIER: "grade",
              Factor(
                Const(
                  CHARACTER_LITERAL: "a"
                )
              )
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                float
              ),
              IDENTIFIER: "a",
              Factor(
                Const(
                  INTEGER_LITERAL: "1"
                )
              ),
              IDENTIFIER: "b",
              Factor(
                Const(
                  INTEGER_LITERAL: "2"
                )
              ),
              IDENTIFIER: "c",
              Factor(
                Const(
                  INTEGER_LITERAL: "3"
                )
              )
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                bool
              ),
              IDENTIFIER: "a",
              IDENTIFIER: "b",
              IDENTIFIER: "c"
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "a",
              Exp(
                IDENTIFIER: "b",
                Exp(
                  IDENTIFIER: "c",
                  Exp(
                    IDENTIFIER: "d",
                    Exp(
                      IDENTIFIER: "e",
                      Factor(
                        Const(
                          INTEGER_LITERAL: "10"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "a",
              Exp(
                IDENTIFIER: "b",
                Factor(
                  Exp(
                    IDENTIFIER: "c",
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Variable_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "zest",
              Exp(
                IDENTIFIER: "b",
                Exp(
                  IDENTIFIER: "c",
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  )
                )
              ),
              IDENTIFIER: "d",
              Factor(
                Const(
                  INTEGER_LITERAL: "10"
                )
              )
            )
          ),
          Block_Item(
            Array_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "arr",
              Const(
                INTEGER_LITERAL: "1"
              )
            )
          ),
          Block_Item(
            Array_Declaration(
              Data_Type(
                bool
              ),
              IDENTIFIER: "array",
              Const(
                INTEGER_LITERAL: "5"
              ),
              Argument_List(
                Factor(
                  Const(
                    INTEGER_LITERAL: "1"
                  )
                ),
                Factor(
                  Const(
                    INTEGER_LITERAL: "2"
                  )
                )
              )
            )
          ),
          Block_Item(
            Array_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "array",
              Const(
                INTEGER_LITERAL: "2"
              ),
              Argument_List(
                Factor(
                  Const(
                    CHARACTER_LITERAL: "c"
                  )
                ),
                Factor(
                  Const(
                    true
                  )
                ),
                Factor(
                  Const(
                    INTEGER_LITERAL: "0"
                  )
                ),
                Factor(
                  Const(
                    FLOAT_LITERAL: "1.0"
                  )
                )
              )
            )
          ),
          Block_Item(
            Array_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "arr",
              Const(
                INTEGER_LITERAL: "3"
              ),
              Argument_List(
                Factor(
                  Factor(
                    IDENTIFIER: "foo",
                    Argument_List(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "5"
                        )
                      )
                    )
                  )
                ),
                Factor(
                  IDENTIFIER: "a",
                  Const(
                    INTEGER_LITERAL: "20"
                  )
                ),
                Factor(
                  IDENTIFIER: "multiply",
                  Argument_List(
                    Factor(
                      IDENTIFIER: "a"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Factor(
                  Const(
                    INTEGER_LITERAL: "1"
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Exp(
                  IDENTIFIER: "b",
                  Exp(
                    IDENTIFIER: "c",
                    Exp(
                      IDENTIFIER: "d",
                      Exp(
                        IDENTIFIER: "e",
                        Factor(
                          Const(
                            INTEGER_LITERAL: "10"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Exp(
                  IDENTIFIER: "b",
                  Factor(
                    Exp(
                      IDENTIFIER: "c",
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Logical_Or(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Logical_Or(
                  Logical_Or(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Logical_Or(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Logical_Or(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "3"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Exp(
                  IDENTIFIER: "b",
                  Logical_Or(
                    Logical_Or(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "1"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Logical_And(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Logical_And(
                  Logical_And(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_And(
                  Logical_And(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Logical_And(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "z",
                Logical_Or(
                  Logical_And(
                    Logical_And(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "10"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "20"
                        )
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "30"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "40"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_And(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Logical_Or(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "3"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Logical_Or(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "3"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Exp(
                  IDENTIFIER: "b",
                  Logical_Or(
                    Logical_Or(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "1"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Equality(
                Factor(
                  IDENTIFIER: "a"
                ),
                Factor(
                  IDENTIFIER: "b"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Equality(
                Factor(
                  IDENTIFIER: "a"
                ),
                Factor(
                  IDENTIFIER: "b"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Equality(
                Equality(
                  Factor(
                    IDENTIFIER: "a"
                  ),
                  Factor(
                    IDENTIFIER: "b"
                  )
                ),
                Factor(
                  IDENTIFIER: "c"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Equality(
                Equality(
                  Factor(
                    IDENTIFIER: "a"
                  ),
                  Factor(
                    IDENTIFIER: "b"
                  )
                ),
                Factor(
                  IDENTIFIER: "c"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Relational(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Relational(
                Factor(
                  IDENTIFIER: "a"
                ),
                Factor(
                  Const(
                    INTEGER_LITERAL: "2"
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Relational(
                Factor(
                  IDENTIFIER: "a"
                ),
                Factor(
                  IDENTIFIER: "b"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Relational(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "5"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "7"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Relational(
                  Relational(
                    Relational(
                      Relational(
                        Factor(
                          Const(
                            INTEGER_LITERAL: "3"
                          )
                        ),
                        Factor(
                          Const(
                            INTEGER_LITERAL: "4"
                          )
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "5"
                        )
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "7"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "7"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Equality(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Relational(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "5"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "8"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Equality(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Relational(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "4"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Additive(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Additive(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Additive(
                  Additive(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Equality(
                  Relational(
                    Additive(
                      Additive(
                        Factor(
                          Const(
                            INTEGER_LITERAL: "1"
                          )
                        ),
                        Factor(
                          Const(
                            INTEGER_LITERAL: "1"
                          )
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "2"
                        )
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Multiplicative(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Multiplicative(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "5"
                    )
                  ),
                  Factor(
                    Const(
                      INTEGER_LITERAL: "2"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Multiplicative(
                Factor(
                  IDENTIFIER: "x"
                ),
                Factor(
                  IDENTIFIER: "y"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Multiplicative(
                Factor(
                  IDENTIFIER: "x"
                ),
                Factor(
                  IDENTIFIER: "y"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Multiplicative(
                Multiplicative(
                  Multiplicative(
                    Factor(
                      IDENTIFIER: "x"
                    ),
                    Factor(
                      IDENTIFIER: "y"
                    )
                  ),
                  Factor(
                    IDENTIFIER: "z"
                  )
                ),
                Factor(
                  IDENTIFIER: "a"
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Exponent(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Exponent(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Expression_Statement(
                Logical_And(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Exponent(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    ),
                    Exponent(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "3"
                        )
                      ),
                      Exponent(
                        Factor(
                          Const(
                            INTEGER_LITERAL: "4"
                          )
                        ),
                        Factor(
                          IDENTIFIER: "func"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  ),
                  Logical_And(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    ),
                    Exponent(
                      Factor(
                        Const(
                          INTEGER_LITERAL: "3"
                        )
                      ),
                      Factor(
                        Const(
                          INTEGER_LITERAL: "4"
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "a",
                Logical_Or(
                  Exponent(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "1"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "2"
                      )
                    )
                  ),
                  Logical_And(
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    ),
                    Factor(
                      Const(
                        INTEGER_LITERAL: "4"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "b",
                Unary_Exp(
                  MINUS: "-",
                  Factor(
                    Const(
                      INTEGER_LITERAL: "1"
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "c",
                Unary_Exp(
                  MINUS: "-",
                  Unary_Exp(
                    MINUS: "-",
                    Unary_Exp(
                      MINUS: "-",
                      Unary_Exp(
                        MINUS: "-",
                        Factor(
                          Const(
                            INTEGER_LITERAL: "3"
                          )
                        )
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "b",
                Exponent(
                  Unary_Exp(
                    MINUS: "-",
                    Factor(
                      Const(
                        INTEGER_LITERAL: "3"
                      )
                    )
                  ),
                  Unary_Exp(
                    MINUS: "-",
                    Factor(
                      Const(
                        INTEGER_LITERAL: "5"
                      )
                    )
                  )
                )
              )
            )
          ),
          Block_Item(
            Statement(
              Exp(
                IDENTIFIER: "c",
                Additive(
                  Factor(
                    Const(
                      INTEGER_LITERAL: "3"
                    )
                  ),
                  Unary_Exp(
                    MINUS: "-",
                    Factor(
                      Const(
                        INTEGER_LITERAL: "5"
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  ),
  Declaration(
    Function_Declaration(
      Data_Type(
        bool
      ),
      IDENTIFIER: "isValid",
      Parameter_List(
        Data_Type(
          bool
        ),
        IDENTIFIER: "x",
        Data_Type(
          int
        ),
        IDENTIFIER: "y",
        Data_Type(
          char
        ),
        IDENTIFIER: "z"
      ),
      Block(
        Block_Item_List(
          Block_Item(
            Variable_Declaration(
              Data_Type(
                int
              ),
              IDENTIFIER: "a",
              IDENTIFIER: "b"
            )
          )
        )
      )
    )
  )
)